// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: recipies.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRecipe = `-- name: CreateRecipe :one
INSERT INTO recipies (id, created_at, updated_at, title, description, author_id) 
VALUES($1, $2, $3, $4, $5, $6)
RETURNING id, created_at, updated_at, title, description, author_id
`

type CreateRecipeParams struct {
	ID          uuid.UUID     `json:"id"`
	CreatedAt   time.Time     `json:"created_at"`
	UpdatedAt   time.Time     `json:"updated_at"`
	Title       string        `json:"title"`
	Description string        `json:"description"`
	AuthorID    uuid.NullUUID `json:"author_id"`
}

func (q *Queries) CreateRecipe(ctx context.Context, arg CreateRecipeParams) (Recipy, error) {
	row := q.db.QueryRowContext(ctx, createRecipe,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Title,
		arg.Description,
		arg.AuthorID,
	)
	var i Recipy
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Description,
		&i.AuthorID,
	)
	return i, err
}
